### ISSUE TITLE
improve clarity of x-axis spacing (dates instead of indices)

### ISSUE THREAD

**Issue by jrdegreeff** [jrdegreeff/health-portrait#60]

**Comment by wli-linda** [comment]
Is this fixed by #82 ?

**Comment by oliviagiandrea** [comment]
fixed by https://github.com/jrdegreeff/health-portrait/pull/82

**Comment by oliviagiandrea** [comment]
![image](https://user-images.githubusercontent.com/71414308/207493117-14631957-0247-4990-bb2f-2e3d22c64f29.png)
