### ISSUE TITLE
Buttons in view more section of log table don't align properly when notes only one line

### ISSUE THREAD

**Issue by jrdegreeff** [jrdegreeff/health-portrait#94]
<img width="1186" alt="Screen Shot 2022-12-11 at 12 22 28 PM" src="https://user-images.githubusercontent.com/19782270/206918673-28246957-dcfb-4df6-b377-b657c45e2a35.png">

**Comment by wli-linda** [comment]
![image](https://user-images.githubusercontent.com/59969293/206922523-95d0dc30-c1eb-4207-9df6-80ac7fa99d88.png)
seems to work on main rn, might be some merging issue? will double check when new PRs are merged in


ah yeah, I think some styling changes for `<p>` in the newest commits interacted with this... will add a scoped style to entrypage
